# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tdfIGTLC5UoilMox_ilb_JNYwcyHP5x
"""

import numpy as np
A = np.arange(12).reshape(3,4)
B = np.array([1,2,3,4])
C = np.array([20,20,40])

print(A.shape)
print(B.shape)
print(C.shape)

print(A)

print(A+B)

D = np.array([[10],[20],[30],[40]])
print(D.shape)

"""A school wants to simulate and store performance records for its students across three subjects. Your task is to generate this data using NumPy, manipulate the array, and save the records to a file.

Tasks
Task 1 — Generate and Inspect the Dataset Using NumPy random functions, create the following columns for 10 students: name (chosen randomly from a list of 5 names), age (random integers between 15 and 18), maths (random integers between 40 and 100), science (random integers between 40 and 100), and english (random integers between 40 and 100). Set np.random.seed(42) before generating any values. Print the shape of the marks array (only the three subject columns) and its dtype.

Task 2 — Reshape and Slice the Marks Array Take the marks array of shape (10, 3) and reshape it into shape (2, 5, 3). Print the reshaped array. Then, from the original (10, 3) marks array, slice and print the marks of the first five students for maths and science only (columns 0 and 1). In a comment, explain what the shape (2, 5, 3) represents in terms of the data.

Task 3 — Save the Records to a File Write all 10 student records to a text file called student_records.txt, with each record on its own line in the format: Name | Age | Maths | Science | English. Use the with statement to open the file. Print a confirmation message after writing. Then open the file in read mode and print all lines to verify the output.



"""

np.random.seed(42)
names = np.random.choice(["Ravi", "Bindu", "Dinakar", "Kumari", "Rajesh"], size = 10)
ages = np.random.randint(15,19, size =10)
maths = np.random.randint(40,101, size =10)
science = np.random.randint(40,101, size =10)
english = np.random.randint(40, 101, size =10)

marks = np.array([maths, science, english])
print(marks.shape)
print(marks.dtype)

trans_marks = marks.T
print(trans_marks.shape)

marks_reshape = trans_marks.reshape(2,5,3)
print(marks_reshape)

sliced_marks = trans_marks[:5,:2]
print(sliced_marks)

with open("student_records.txt", "w") as file:
  for i in range(10):
    line = f"{names[i]} | {ages[i]} | {maths[i]} | {science[i]} | {english[i]}\n"
    file.write(line)
print("Records written successfully")

with open("student_records.txt", "r") as file:
  l = file.readlines()

for line in l:
  print(line.strip())

np.random.seed(7)
names1 = np.random.choice(["Ravi", "Bindu", "Dinakar", "Kumari", "Rajesh"], size = 10)
ages1 = np.random.randint(15,19, size =10)
maths1 = np.random.randint(40,101, size =10)
science1 = np.random.randint(40,101, size =10)
english1 = np.random.randint(40, 101, size =10)

marks1 = np.array([maths1, science1, english1])
print(marks1.shape)
print(marks1.dtype)

trans_marks1 = marks1.T
print(trans_marks1.shape)

marks1_reshape = trans_marks1.reshape(2,5,3)
print(marks1_reshape)

sliced1_marks = trans_marks1[:5,:2]
print(sliced1_marks)

with open("student_records2.txt", "a") as file:
  d = "Name---Age---Maths---Science---English\n"
  file.write(d)
  for i in range(10):
    line = f"{names1[i]}---{ages1[i]} | {maths1[i]} | {science1[i]} | {english1[i]}\n"
    file.write(line)
print("Records written successfully")



list_ex = [1,2,3,4]
arr = np.array(list_ex)
print(arr.shape)

ar1 = np.arange(0,10,2)
print(ar1)